/* tslint:disable */
/* eslint-disable */
/**
 * Tickets API
 * REST API для управления билетами, людьми, событиями и площадками.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Event } from './event';

/**
 *
 * @export
 * @interface EventsEnvelope
 */
export interface EventsEnvelope {
  /**
   *
   * @type {Array<Event>}
   * @memberof EventsEnvelope
   */
  events: Array<Event>;
}
