/* tslint:disable */
/* eslint-disable */
/**
 * Tickets API
 * REST API для управления билетами, людьми, событиями и площадками.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Ticket } from './ticket';

/**
 *
 * @export
 * @interface TicketsEnvelope
 */
export interface TicketsEnvelope {
  /**
   *
   * @type {Array<Ticket>}
   * @memberof TicketsEnvelope
   */
  tickets: Array<Ticket>;
}
