/* tslint:disable */
/* eslint-disable */
/**
 * Tickets API
 * REST API для управления билетами, людьми, событиями и площадками.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { Person } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
/**
 * PersonsApi - axios parameter creator
 * @export
 */
export const PersonsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Создать человека
     * @param {Person} person
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addPerson: async (
      person: Person,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'person' is not null or undefined
      assertParamExists('addPerson', 'person', person);
      const localVarPath = `/add_person`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        person,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Получить список людей
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPersons: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/get_persons`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PersonsApi - functional programming interface
 * @export
 */
export const PersonsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PersonsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Создать человека
     * @param {Person} person
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addPerson(
      person: Person,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addPerson(person, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PersonsApi.addPerson']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Получить список людей
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPersons(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPersons(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PersonsApi.getPersons']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PersonsApi - factory interface
 * @export
 */
export const PersonsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = PersonsApiFp(configuration);
  return {
    /**
     *
     * @summary Создать человека
     * @param {Person} person
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addPerson(person: Person, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
      return localVarFp.addPerson(person, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Получить список людей
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPersons(options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
      return localVarFp.getPersons(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * PersonsApi - object-oriented interface
 * @export
 * @class PersonsApi
 * @extends {BaseAPI}
 */
export class PersonsApi extends BaseAPI {
  /**
   *
   * @summary Создать человека
   * @param {Person} person
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PersonsApi
   */
  public addPerson(person: Person, options?: RawAxiosRequestConfig) {
    return PersonsApiFp(this.configuration)
      .addPerson(person, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Получить список людей
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PersonsApi
   */
  public getPersons(options?: RawAxiosRequestConfig) {
    return PersonsApiFp(this.configuration)
      .getPersons(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
