/* tslint:disable */
/* eslint-disable */
/**
 * Tickets API
 * REST API для управления билетами, людьми, событиями и площадками.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { Venue } from '../models';
/**
 * VenuesApi - axios parameter creator
 * @export
 */
export const VenuesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Создать площадку
     * @param {Venue} venue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addVenue: async (venue: Venue, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'venue' is not null or undefined
      assertParamExists('addVenue', 'venue', venue);
      const localVarPath = `/add_venue`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        venue,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Получить список площадок
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVenues: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/get_venues`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * VenuesApi - functional programming interface
 * @export
 */
export const VenuesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = VenuesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Создать площадку
     * @param {Venue} venue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addVenue(
      venue: Venue,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addVenue(venue, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['VenuesApi.addVenue']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Получить список площадок
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getVenues(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getVenues(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['VenuesApi.getVenues']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * VenuesApi - factory interface
 * @export
 */
export const VenuesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = VenuesApiFp(configuration);
  return {
    /**
     *
     * @summary Создать площадку
     * @param {Venue} venue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addVenue(venue: Venue, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
      return localVarFp.addVenue(venue, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Получить список площадок
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVenues(options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
      return localVarFp.getVenues(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * VenuesApi - object-oriented interface
 * @export
 * @class VenuesApi
 * @extends {BaseAPI}
 */
export class VenuesApi extends BaseAPI {
  /**
   *
   * @summary Создать площадку
   * @param {Venue} venue
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VenuesApi
   */
  public addVenue(venue: Venue, options?: RawAxiosRequestConfig) {
    return VenuesApiFp(this.configuration)
      .addVenue(venue, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Получить список площадок
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VenuesApi
   */
  public getVenues(options?: RawAxiosRequestConfig) {
    return VenuesApiFp(this.configuration)
      .getVenues(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
